### ISSUE TITLE
Old keywords don't work anymore

### ISSUE THREAD

**Issue by Regenhardt** [jbis9051/JamesSOBot#10]
So before you could make commands using <user> to mention the user calling the command, <message> for the message calling the command, and substitutions in the command where done using $0,$1... syntax.

That seems to have changed to syntax like {0}...and broke lots of commands. Also <user> doesn't work at all anymore.

This change should be adressed, either by going back to the old syntax or changing the existing commands to use the new syntax.

**Comment by jbis9051** [comment]
I think it would be best to go to the new syntax. I will look into building a migration script for the old commands.

**Comment by jbis9051** [comment]
The only thing missing is the random function.
