### ISSUE TITLE
Link to room rules is deprecated. Update needed.

### ISSUE THREAD

**Issue by TheCriticalCritic** [jbis9051/JamesSOBot#17]
![grafik](https://user-images.githubusercontent.com/72605853/115221602-25bfbe00-a10a-11eb-91f7-e5d749184ed4.png)

The url just has to be replaced. As I don't  have the new one here is just the issue.

**Comment by jbis9051** [comment]
What URL?

**Comment by TheCriticalCritic** [comment]
This one https://rlemon.github.com/so-chat-javascript-rules/
It is sent with standard greeting message:
"Welcome to the JavaScript chat! Please review the room rules (here would be the link). If you have a question, just post it, and if anyone's free and interested they'll help. If you want to report an abusive user or a problem in this room, visit our meta. "

**Comment by jbis9051** [comment]
@TheCriticalCritic Not sure where you are seeing that. https://github.com/jbis9051/JamesSOBot/blob/master/packages/platforms/so/src/app.ts#L50

**Comment by jbis9051** [comment]
Ah. Seems like it's been fixed since this issue was created. Thanks! 

https://chat.stackoverflow.com/transcript/message/53052099#53052099
