### ISSUE TITLE
Add a timeout to unformatted code to give the user a chance to edit.

### ISSUE THREAD

**Issue by xbenjii** [jbis9051/JamesSOBot#7]

**Comment by jbis9051** [comment]
Added feature in https://github.com/jbis9051/JamesSOBot/commit/b34dbeec234894bd4bf014e094e58747842ce567.

 Still needs to work to extend timeout, edit unformatted message to alert user of timeout, and to possibly make the check more efficient as per [this](https://chat.stackoverflow.com/transcript/message/48349992#48349992).

**Comment by jbis9051** [comment]
Time was added in a recent commit.
